In [79]:
import pandas as pd
import numpy as np

In [80]:
arr2d_2 = np.array([[100],
          [100],
          [100],
          [100]])

In [81]:
df4 = pd.DataFrame(data=arr2d_2,columns=['class d'])
df4

class d
0      100
1      100
2      100
3      100

In [82]:
arr2d_3 = np.array([
          [108],
          [154],
          [193]])

In [83]:
df5 = pd.DataFrame(data=arr2d_3,columns=['class d'])
df5

class d
0      108
1      154
2      193

In [84]:
pd.concat([df4,df5],ignore_index=True)

class d
0      100
1      100
2      100
3      100
4      108
5      154
6      193

In [85]:
data2 = np.array([[87,85],
                 [89,90],
                ])

In [86]:
df2 = pd.DataFrame(data=data2,columns=['class a','class b'])
df2

class a  class b
0       87       85
1       89       90

In [87]:
arr2d_2 = np.array([[100],
          [100],
          [100],
          [100]])

In [88]:
myList = [1.1, 2.2, 3.3]
list(map(int, myList))

[1, 2, 3]

In [89]:
import openpyxl.worksheet

In [90]:
np.random.randint(0, 255, size=5)

array([205, 175, 230, 232,  32])

In [91]:
np.random.random(0, 255, size=(5, 5))

TypeError: random() takes at most 1 positional argument (2 given)

In [ ]:
ary = np.array( [[ 1, 1 ] , [ 2 , 2 ] ])
ary += ary
ary += 10
ary

array([[12, 12],
       [14, 14]])

In [ ]:
ary = np.array( [ 0 , 1, 2 , 3, 4 ] )
ary2 = ary[0:2]
ary2[:] = 88
ary


array([88, 88,  2,  3,  4])

In [ ]:
ary1 = [ 1, 2, 3, 4 ]
ary2 = []
for i in range(3,-1,-1):
    ary2.append(ary1[i])
print(ary1)
print(ary2)


[1, 2, 3, 4]
[4, 3, 2, 1]


In [ ]:
num = 0
if num > 0 :
    print("케이스1", end = ' ')
else :
    print("케이스2", end = ' ')
print("케이스3", end = ' ')


케이스2 케이스3 

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
titanic = pd.read_csv('C:/ex/data/archive (1)/tested - 복사본.csv')
titanic

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


In [ ]:
titanic['Age'].mean()

30.272590361445783

In [ ]:
mean = round(titanic['Age'].mean(),1)

In [ ]:
titanic['Age'].fillna(mean,inplace=True)

C:\Users\acy\AppData\Local\Temp\ipykernel_6940\2455009795.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['Age'].fillna(mean,inplace=True)


In [ ]:
titanic['Age'].isna().sum()

0

In [ ]:
titanic['Age'].iloc[5]

14.0

In [ ]:
import numpy as np
data = [1,2,3,4,5]
np.var(data)
np.std(data)
