In [1]:
import pandas as pd
import numpy as np

In [2]:
arr2d_2 = np.array([[100],
          [100],
          [100],
          [100]])

In [3]:
df4 = pd.DataFrame(data=arr2d_2,columns=['class d'])
df4

class d
0      100
1      100
2      100
3      100

In [4]:
arr2d_3 = np.array([
          [108],
          [154],
          [193]])

In [5]:
df5 = pd.DataFrame(data=arr2d_3,columns=['class d'])
df5

class d
0      108
1      154
2      193

In [6]:
pd.concat([df4,df5],ignore_index=True)

class d
0      100
1      100
2      100
3      100
4      108
5      154
6      193

In [7]:
data2 = np.array([[87,85],
                 [89,90],
                ])

In [8]:
df2 = pd.DataFrame(data=data2,columns=['class a','class b'])
df2

class a  class b
0       87       85
1       89       90

In [9]:
arr2d_2 = np.array([[100],
          [100],
          [100],
          [100]])

In [10]:
myList = [1.1, 2.2, 3.3]
list(map(int, myList))

[1, 2, 3]

In [12]:
import openpyxl.worksheet

In [13]:
np.random.randint(0, 255, size=5)

array([125, 176, 219, 114, 120])

In [15]:
# np.random.random(0, 255, size=(5, 5))

In [16]:
ary = np.array( [[ 1, 1 ] , [ 2 , 2 ] ])
ary += ary
ary += 10
ary

array([[12, 12],
       [14, 14]])

In [17]:
ary = np.array( [ 0 , 1, 2 , 3, 4 ] )
ary2 = ary[0:2]
ary2[:] = 88
ary


array([88, 88,  2,  3,  4])

In [18]:
ary1 = [ 1, 2, 3, 4 ]
ary2 = []
for i in range(3,-1,-1):
    ary2.append(ary1[i])
print(ary1)
print(ary2)


[1, 2, 3, 4]
[4, 3, 2, 1]


In [19]:
num = 0
if num > 0 :
    print("케이스1", end = ' ')
else :
    print("케이스2", end = ' ')
print("케이스3", end = ' ')


케이스2 케이스3 

In [21]:
import numpy as np
import pandas as pd
import seaborn as sns

In [23]:
FileNotFoundError

# titanic = pd.read_csv('C:/ex/data/archive (1)/tested - 복사본.csv')
# titanic

FileNotFoundError

In [24]:
# titanic.info()

In [25]:
# titanic['Age'].mean()

In [26]:
# mean = round(titanic['Age'].mean(),1)

In [27]:
# titanic['Age'].fillna(mean,inplace=True)

In [28]:
# titanic['Age'].isna().sum()

In [29]:
# titanic['Age'].iloc[5]

In [30]:
# import numpy as np
# data = [1,2,3,4,5]
# np.var(data)
# np.std(data)