In [ ]:
# ! pip install 패키지

In [2]:
!pwd

/content


In [3]:
!find / -name 'numpy*'

/usr/include/boost/python/numpy
/usr/include/boost/python/numpy/numpy_object_mgr_traits.hpp
/usr/include/boost/python/numpy.hpp
/usr/local/lib/python3.10/dist-packages/tensorflow/include/tsl/python/lib/core/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/pybind11/include/pybind11/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/pybind11/_virtual_includes/pybind11/pybind11/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include/numpy
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include/numpy/numpyconfig.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/tensorflow/tsl/python/lib/core/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/dtensor/python/numpy_util.py
/usr/local/lib/python3.10/dist-packages/tensorflow/d

In [5]:
import numpy

In [6]:
import numpy as np #엘리어스 처리

In [3]:
# help(np.array)

리스트: 자료형을 마음대로. 짬뽕
array: 동일한 타입

In [4]:
# np.array(1,2,3)

In [5]:
arr1 = np.array([1,2,3])

In [6]:
type(arr1)

numpy.ndarray

nd

n은 숫자

d는 디멘션

In [7]:
arr1.shape

(3,)

In [8]:
arr1.size

3

In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [12]:
arr2.shape

(2, 3)

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2.size

6

In [16]:
arr1.ndim

1

In [22]:
arr2.shape #몇 행 몇 열 짜리인지

(2, 3)

In [23]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [24]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [25]:
arr3.size

12

In [26]:
arr3.shape

(2, 2, 3)

In [27]:
arr4 = np.array([[1],
                [2],
                [-1.0],
                [3.14]])

In [28]:
arr4

array([[ 1.  ],
       [ 2.  ],
       [-1.  ],
       [ 3.14]])

In [30]:
arr4. shape

(4, 1)

In [31]:
arr4.ndim

2

In [34]:
arr5 = np.array([[[[1,2,-1.0,3.14]]]])

In [35]:
arr5

array([[[[ 1.  ,  2.  , -1.  ,  3.14]]]])

In [37]:
arr5.ndim

4

In [38]:
# 배열(너파이 배열,np.array) 계산

In [39]:
mu = np.array([1,2,3])

In [40]:
nu = np.array([4,4,4])

In [42]:
mu+nu

array([5, 6, 7])

In [43]:
2*(mu+nu)

array([10, 12, 14])

In [44]:
# 행렬의 연산

In [45]:
a = np.array([[3,6],[5,7]])

In [46]:
a

array([[3, 6],
       [5, 7]])

In [47]:
b = np.array([[2,6],[5,8]])

In [48]:
b

array([[2, 6],
       [5, 8]])

In [49]:
a+b

array([[ 5, 12],
       [10, 15]])

In [51]:
a-b

array([[0, 0],
       [0, 0]])

In [52]:
c = np.array([[3,6,9],[5,8,7]])

In [54]:
d = np.array([[3,6,9],[5,8]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [53]:
a+c #모양이 안 맞으면 에러가 난다

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [55]:
np.all([True,True,True])

True

In [56]:
np.all([True,False])

False

In [57]:
np.any([False, True])

True

In [59]:
np.array([[3,6],
         [4,5]]
         )

array([[3, 6],
       [4, 5]])

In [60]:
a = np.array([[3,6],
         [4,5]]
         )

In [63]:
a

array([[3, 6],
       [4, 5]])

In [69]:
a.transpose() #전치행렬

array([[3, 4],
       [6, 5]])

In [70]:
a.transpose().transpose()

array([[3, 6],
       [4, 5]])

In [71]:
a

array([[3, 6],
       [4, 5]])

In [72]:
a.T

array([[3, 4],
       [6, 5]])

In [73]:
a

array([[3, 6],
       [4, 5]])

In [74]:
b = np.array([[9,5,6],
         [4,5,2]]
         )

In [75]:
b

array([[9, 5, 6],
       [4, 5, 2]])

In [76]:
b.transpose()

array([[9, 4],
       [5, 5],
       [6, 2]])

In [77]:
b.transpose().transpose()

array([[9, 5, 6],
       [4, 5, 2]])

In [81]:
a = np.array([[3,7],
              [2,4]])

In [82]:
b = np.array([[1,5],
              [3,2]])

In [84]:
a*b

array([[ 3, 35],
       [ 6,  8]])

In [92]:
b*a

array([[ 3, 35],
       [ 6,  8]])

In [86]:
print(3/1)
print(7/5)
print(2/3)
print(4/2)

3.0
1.4
0.6666666666666666
2.0


In [87]:
a/b

array([[3.        , 1.4       ],
       [0.66666667, 2.        ]])

In [93]:
b/a

array([[0.33333333, 0.71428571],
       [1.5       , 0.5       ]])

In [94]:
a+b

array([[ 4, 12],
       [ 5,  6]])

In [95]:
b+a

array([[ 4, 12],
       [ 5,  6]])

In [96]:
a-b

array([[ 2,  2],
       [-1,  2]])

In [97]:
b-a

array([[-2, -2],
       [ 1, -2]])

In [98]:
a = np.array([[1,2,3],[4,5,6]])
b =np.array([[7,8],[9,10],[11,12]])

In [99]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [100]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [7]:
a = np.array([[1,1,2],[2,1,1]])
b = np.array([[1,1],[2,1],[1,3]])

In [8]:
a.dot(b)

array([[5, 8],
       [5, 6]])

In [9]:
np.dot(a,b)

array([[5, 8],
       [5, 6]])