In [135]:
import numpy as np

In [136]:
arr = np.array([[1,2,3],[4,5,6]])

In [137]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
arr.ndim

2

In [139]:
arr = arr.reshape(3,2)

In [140]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [141]:
arr = np.delete(arr,1,axis = 0)

In [142]:
arr

array([[1, 2],
       [5, 6]])

In [143]:
arr = np.delete(arr,1,axis = 1)

In [144]:
arr

array([[1],
       [5]])

In [145]:
arr = np.append(arr,[[7,8],[7,8]],axis = 1)

In [146]:
arr

array([[1, 7, 8],
       [5, 7, 8]])

In [147]:
arr = np.append(arr,[[8,2,9]],axis = 0)

In [148]:
arr

array([[1, 7, 8],
       [5, 7, 8],
       [8, 2, 9]])

In [149]:
arr = np.append(arr,[[1],[1],[1]],axis = 1)

In [150]:
arr

array([[1, 7, 8, 1],
       [5, 7, 8, 1],
       [8, 2, 9, 1]])

In [151]:
arr = arr.reshape(2,2,3)

In [152]:
arr

array([[[1, 7, 8],
        [1, 5, 7]],

       [[8, 1, 8],
        [2, 9, 1]]])

In [153]:
arr.reshape(6,2)

array([[1, 7],
       [8, 1],
       [5, 7],
       [8, 1],
       [8, 2],
       [9, 1]])

In [156]:
arr.reshape(-1)

array([1, 7, 8, 1, 5, 7, 8, 1, 8, 2, 9, 1])

In [ ]:
arr1 = np.array([])