In [32]:
import pandas as pd
import numpy as np

In [33]:
arr2d_2 = np.array([[100],
          [100],
          [100],
          [100]])

In [34]:
df4 = pd.DataFrame(data=arr2d_2,columns=['class d'])
df4

class d
0      100
1      100
2      100
3      100

In [35]:
arr2d_3 = np.array([
          [108],
          [154],
          [193]])

In [36]:
df5 = pd.DataFrame(data=arr2d_3,columns=['class d'])
df5

class d
0      108
1      154
2      193

In [37]:
pd.concat([df4,df5],ignore_index=True)

class d
0      100
1      100
2      100
3      100
4      108
5      154
6      193

In [38]:
data2 = np.array([[87,85],
                 [89,90],
                ])

In [39]:
df2 = pd.DataFrame(data=data2,columns=['class a','class b'])
df2

class a  class b
0       87       85
1       89       90

In [40]:
arr2d_2 = np.array([[100],
          [100],
          [100],
          [100]])

In [41]:
myList = [1.1, 2.2, 3.3]
list(map(int, myList))

[1, 2, 3]

In [46]:
import openpyxl.worksheet

In [51]:
np.random.randint(0, 255, size=5)

array([108,  26, 148, 120, 245])

In [53]:
np.random.random(0, 255, size=(5, 5))

TypeError: random() takes at most 1 positional argument (2 given)

In [54]:
ary = np.array( [[ 1, 1 ] , [ 2 , 2 ] ])
ary += ary
ary += 10
ary

array([[12, 12],
       [14, 14]])

In [55]:
ary = np.array( [ 0 , 1, 2 , 3, 4 ] )
ary2 = ary[0:2]
ary2[:] = 88
ary


array([88, 88,  2,  3,  4])

In [5]:
ary1 = [ 1, 2, 3, 4 ]
ary2 = []
for i in range(3,-1,-1):
    ary2.append(ary1[i])
print(ary1)
print(ary2)


[1, 2, 3, 4]
[4, 3, 2, 1]


In [6]:
num = 0
if num > 0 :
    print("케이스1", end = ' ')
else :
    print("케이스2", end = ' ')
print("케이스3", end = ' ')


케이스2 케이스3 